AllCops:
  Exclude:
    - 'db/*/*'
    - 'db/*'
    - 'config/*/*'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false